# Generated by Django 4.0 on 2023-06-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
