# Generated by Django 4.0 on 2023-06-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_first_name',
        ),
    ]
