# Generated by Django 4.0 on 2023-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cart_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='dfrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='dto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='ncottage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
